version: '3.8'

services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: my_secure_password_1
      DB_MYSQL_NAME: npm_db
    volumes:
      - /docker/swarmfs/npm/nginx_data:/data
      - /docker/swarmfs/npm/nginx_letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - npm_network
      - npm_db_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password_2
      MYSQL_DATABASE: npm_db
      MYSQL_USER: npm
      MYSQL_PASSWORD: my_secure_password_1
    volumes:
      - /docker/swarmfs/npm/db_data:/var/lib/mysql
    networks:
      - npm_db_network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  npm_network:
    driver: overlay
  npm_db_network:
    driver: overlay

volumes:
  nginx_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/swarmfs/npm/nginx_data
  nginx_letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/swarmfs/npm/nginx_letsencrypt
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/swarmfs/npm/db_data
